# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, neutron_reaction, data):
    offset = neutron_reaction["xs_offset"]
    return data[offset + index]


@njit
def xs_all(neutron_reaction, data):
    start = neutron_reaction["xs_offset"]
    size = neutron_reaction["xs_length"]
    end = start + size
    return data[start:end]


@njit
def xs_last(neutron_reaction, data):
    start = neutron_reaction["xs_offset"]
    size = neutron_reaction["xs_length"]
    end = start + size
    return data[end - 1]


@njit
def xs_chunk(start, length, neutron_reaction, data):
    start += neutron_reaction["xs_offset"]
    end = start + length
    return data[start:end]
