# The following is automatically generated by code_factory.py

from numba import njit


@njit
def energy_bounds(index, weight_windows, data):
    offset = weight_windows["energy_bounds_offset"]
    return data[offset + index]


@njit
def energy_bounds_all(weight_windows, data):
    start = weight_windows["energy_bounds_offset"]
    size = weight_windows["energy_bounds_length"]
    end = start + size
    return data[start:end]


@njit
def energy_bounds_last(weight_windows, data):
    start = weight_windows["energy_bounds_offset"]
    size = weight_windows["energy_bounds_length"]
    end = start + size
    return data[end - 1]


@njit
def energy_bounds_chunk(start, length, weight_windows, data):
    start += weight_windows["energy_bounds_offset"]
    end = start + length
    return data[start:end]


@njit
def lower_weights(index_1, index_2, index_3, index_4, weight_windows, data):
    offset = weight_windows["lower_weights_offset"]
    stride_2 = weight_windows["Nx"]
    stride_3 = weight_windows["Ny"]
    stride_4 = weight_windows["Nz"]
    return data[offset + index_1 * stride_2 * stride_3 * stride_4 + index_2 * stride_3 * stride_4 + index_3 * stride_4 + index_4]


@njit
def lower_weights_chunk(start, length, weight_windows, data):
    start += weight_windows["lower_weights_offset"]
    end = start + length
    return data[start:end]


@njit
def target_weights(index_1, index_2, index_3, index_4, weight_windows, data):
    offset = weight_windows["target_weights_offset"]
    stride_2 = weight_windows["Nx"]
    stride_3 = weight_windows["Ny"]
    stride_4 = weight_windows["Nz"]
    return data[offset + index_1 * stride_2 * stride_3 * stride_4 + index_2 * stride_3 * stride_4 + index_3 * stride_4 + index_4]


@njit
def target_weights_chunk(start, length, weight_windows, data):
    start += weight_windows["target_weights_offset"]
    end = start + length
    return data[start:end]


@njit
def upper_weights(index_1, index_2, index_3, index_4, weight_windows, data):
    offset = weight_windows["upper_weights_offset"]
    stride_2 = weight_windows["Nx"]
    stride_3 = weight_windows["Ny"]
    stride_4 = weight_windows["Nz"]
    return data[offset + index_1 * stride_2 * stride_3 * stride_4 + index_2 * stride_3 * stride_4 + index_3 * stride_4 + index_4]


@njit
def upper_weights_chunk(start, length, weight_windows, data):
    start += weight_windows["upper_weights_offset"]
    end = start + length
    return data[start:end]
