# The following is automatically generated by code_factory.py

from numba import njit


@njit
def subshell_x_IDs(index, electron_ionization_reaction, data, value):
    offset = electron_ionization_reaction["subshell_x_IDs_offset"]
    data[offset + index] = value


@njit
def subshell_x_IDs_all(electron_ionization_reaction, data, value):
    start = electron_ionization_reaction["subshell_x_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_x"]
    end = start + size
    data[start:end] = value


@njit
def subshell_x_IDs_last(electron_ionization_reaction, data, value):
    start = electron_ionization_reaction["subshell_x_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_x"]
    end = start + size
    data[end - 1] = value


@njit
def subshell_x_IDs_chunk(start, length, electron_ionization_reaction, data, value):
    start += electron_ionization_reaction["subshell_x_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def subshell_product_IDs(index, electron_ionization_reaction, data, value):
    offset = electron_ionization_reaction["subshell_product_IDs_offset"]
    data[offset + index] = value


@njit
def subshell_product_IDs_all(electron_ionization_reaction, data, value):
    start = electron_ionization_reaction["subshell_product_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_product"]
    end = start + size
    data[start:end] = value


@njit
def subshell_product_IDs_last(electron_ionization_reaction, data, value):
    start = electron_ionization_reaction["subshell_product_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_product"]
    end = start + size
    data[end - 1] = value


@njit
def subshell_product_IDs_chunk(start, length, electron_ionization_reaction, data, value):
    start += electron_ionization_reaction["subshell_product_IDs_offset"]
    end = start + length
    data[start:end] = value
