# The following is automatically generated by code_factory.py

from numba import njit


@njit
def electron_xs_energy_grid(index, element, data, value):
    offset = element["electron_xs_energy_grid_offset"]
    data[offset + index] = value


@njit
def electron_xs_energy_grid_all(element, data, value):
    start = element["electron_xs_energy_grid_offset"]
    size = element["electron_xs_energy_grid_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_xs_energy_grid_last(element, data, value):
    start = element["electron_xs_energy_grid_offset"]
    size = element["electron_xs_energy_grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_xs_energy_grid_chunk(start, length, element, data, value):
    start += element["electron_xs_energy_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_total_xs(index, element, data, value):
    offset = element["electron_total_xs_offset"]
    data[offset + index] = value


@njit
def electron_total_xs_all(element, data, value):
    start = element["electron_total_xs_offset"]
    size = element["electron_total_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_total_xs_last(element, data, value):
    start = element["electron_total_xs_offset"]
    size = element["electron_total_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_total_xs_chunk(start, length, element, data, value):
    start += element["electron_total_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_ionization_xs(index, element, data, value):
    offset = element["electron_ionization_xs_offset"]
    data[offset + index] = value


@njit
def electron_ionization_xs_all(element, data, value):
    start = element["electron_ionization_xs_offset"]
    size = element["electron_ionization_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_ionization_xs_last(element, data, value):
    start = element["electron_ionization_xs_offset"]
    size = element["electron_ionization_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_ionization_xs_chunk(start, length, element, data, value):
    start += element["electron_ionization_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_elastic_xs(index, element, data, value):
    offset = element["electron_elastic_xs_offset"]
    data[offset + index] = value


@njit
def electron_elastic_xs_all(element, data, value):
    start = element["electron_elastic_xs_offset"]
    size = element["electron_elastic_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_elastic_xs_last(element, data, value):
    start = element["electron_elastic_xs_offset"]
    size = element["electron_elastic_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_elastic_xs_chunk(start, length, element, data, value):
    start += element["electron_elastic_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_excitation_xs(index, element, data, value):
    offset = element["electron_excitation_xs_offset"]
    data[offset + index] = value


@njit
def electron_excitation_xs_all(element, data, value):
    start = element["electron_excitation_xs_offset"]
    size = element["electron_excitation_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_excitation_xs_last(element, data, value):
    start = element["electron_excitation_xs_offset"]
    size = element["electron_excitation_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_excitation_xs_chunk(start, length, element, data, value):
    start += element["electron_excitation_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_bremsstrahlung_xs(index, element, data, value):
    offset = element["electron_bremsstrahlung_xs_offset"]
    data[offset + index] = value


@njit
def electron_bremsstrahlung_xs_all(element, data, value):
    start = element["electron_bremsstrahlung_xs_offset"]
    size = element["electron_bremsstrahlung_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_bremsstrahlung_xs_last(element, data, value):
    start = element["electron_bremsstrahlung_xs_offset"]
    size = element["electron_bremsstrahlung_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_bremsstrahlung_xs_chunk(start, length, element, data, value):
    start += element["electron_bremsstrahlung_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_ionization_reaction_IDs(index, element, data, value):
    offset = element["electron_ionization_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def electron_ionization_reaction_IDs_all(element, data, value):
    start = element["electron_ionization_reaction_IDs_offset"]
    size = element["N_electron_ionization_reaction"]
    end = start + size
    data[start:end] = value


@njit
def electron_ionization_reaction_IDs_last(element, data, value):
    start = element["electron_ionization_reaction_IDs_offset"]
    size = element["N_electron_ionization_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def electron_ionization_reaction_IDs_chunk(start, length, element, data, value):
    start += element["electron_ionization_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_elastic_scattering_reaction_IDs(index, element, data, value):
    offset = element["electron_elastic_scattering_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def electron_elastic_scattering_reaction_IDs_all(element, data, value):
    start = element["electron_elastic_scattering_reaction_IDs_offset"]
    size = element["N_electron_elastic_scattering_reaction"]
    end = start + size
    data[start:end] = value


@njit
def electron_elastic_scattering_reaction_IDs_last(element, data, value):
    start = element["electron_elastic_scattering_reaction_IDs_offset"]
    size = element["N_electron_elastic_scattering_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def electron_elastic_scattering_reaction_IDs_chunk(start, length, element, data, value):
    start += element["electron_elastic_scattering_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_excitation_reaction_IDs(index, element, data, value):
    offset = element["electron_excitation_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def electron_excitation_reaction_IDs_all(element, data, value):
    start = element["electron_excitation_reaction_IDs_offset"]
    size = element["N_electron_excitation_reaction"]
    end = start + size
    data[start:end] = value


@njit
def electron_excitation_reaction_IDs_last(element, data, value):
    start = element["electron_excitation_reaction_IDs_offset"]
    size = element["N_electron_excitation_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def electron_excitation_reaction_IDs_chunk(start, length, element, data, value):
    start += element["electron_excitation_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_bremsstrahlung_reaction_IDs(index, element, data, value):
    offset = element["electron_bremsstrahlung_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def electron_bremsstrahlung_reaction_IDs_all(element, data, value):
    start = element["electron_bremsstrahlung_reaction_IDs_offset"]
    size = element["N_electron_bremsstrahlung_reaction"]
    end = start + size
    data[start:end] = value


@njit
def electron_bremsstrahlung_reaction_IDs_last(element, data, value):
    start = element["electron_bremsstrahlung_reaction_IDs_offset"]
    size = element["N_electron_bremsstrahlung_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def electron_bremsstrahlung_reaction_IDs_chunk(start, length, element, data, value):
    start += element["electron_bremsstrahlung_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def electron_ionization_subshell_binding_energy(index, element, data, value):
    offset = element["electron_ionization_subshell_binding_energy_offset"]
    data[offset + index] = value


@njit
def electron_ionization_subshell_binding_energy_all(element, data, value):
    start = element["electron_ionization_subshell_binding_energy_offset"]
    size = element["electron_ionization_subshell_binding_energy_length"]
    end = start + size
    data[start:end] = value


@njit
def electron_ionization_subshell_binding_energy_last(element, data, value):
    start = element["electron_ionization_subshell_binding_energy_offset"]
    size = element["electron_ionization_subshell_binding_energy_length"]
    end = start + size
    data[end - 1] = value


@njit
def electron_ionization_subshell_binding_energy_chunk(start, length, element, data, value):
    start += element["electron_ionization_subshell_binding_energy_offset"]
    end = start + length
    data[start:end] = value
