# The following is automatically generated by code_factory.py

from numba import njit


@njit
def neutron_xs_energy_grid(index, nuclide, data, value):
    offset = nuclide["neutron_xs_energy_grid_offset"]
    data[offset + index] = value


@njit
def neutron_xs_energy_grid_all(nuclide, data, value):
    start = nuclide["neutron_xs_energy_grid_offset"]
    size = nuclide["neutron_xs_energy_grid_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_xs_energy_grid_last(nuclide, data, value):
    start = nuclide["neutron_xs_energy_grid_offset"]
    size = nuclide["neutron_xs_energy_grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_xs_energy_grid_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_xs_energy_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_total_xs(index, nuclide, data, value):
    offset = nuclide["neutron_total_xs_offset"]
    data[offset + index] = value


@njit
def neutron_total_xs_all(nuclide, data, value):
    start = nuclide["neutron_total_xs_offset"]
    size = nuclide["neutron_total_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_total_xs_last(nuclide, data, value):
    start = nuclide["neutron_total_xs_offset"]
    size = nuclide["neutron_total_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_total_xs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_total_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_elastic_xs(index, nuclide, data, value):
    offset = nuclide["neutron_elastic_xs_offset"]
    data[offset + index] = value


@njit
def neutron_elastic_xs_all(nuclide, data, value):
    start = nuclide["neutron_elastic_xs_offset"]
    size = nuclide["neutron_elastic_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_elastic_xs_last(nuclide, data, value):
    start = nuclide["neutron_elastic_xs_offset"]
    size = nuclide["neutron_elastic_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_elastic_xs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_elastic_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_capture_xs(index, nuclide, data, value):
    offset = nuclide["neutron_capture_xs_offset"]
    data[offset + index] = value


@njit
def neutron_capture_xs_all(nuclide, data, value):
    start = nuclide["neutron_capture_xs_offset"]
    size = nuclide["neutron_capture_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_capture_xs_last(nuclide, data, value):
    start = nuclide["neutron_capture_xs_offset"]
    size = nuclide["neutron_capture_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_capture_xs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_capture_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_inelastic_xs(index, nuclide, data, value):
    offset = nuclide["neutron_inelastic_xs_offset"]
    data[offset + index] = value


@njit
def neutron_inelastic_xs_all(nuclide, data, value):
    start = nuclide["neutron_inelastic_xs_offset"]
    size = nuclide["neutron_inelastic_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_inelastic_xs_last(nuclide, data, value):
    start = nuclide["neutron_inelastic_xs_offset"]
    size = nuclide["neutron_inelastic_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_inelastic_xs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_inelastic_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_fission_xs(index, nuclide, data, value):
    offset = nuclide["neutron_fission_xs_offset"]
    data[offset + index] = value


@njit
def neutron_fission_xs_all(nuclide, data, value):
    start = nuclide["neutron_fission_xs_offset"]
    size = nuclide["neutron_fission_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_fission_xs_last(nuclide, data, value):
    start = nuclide["neutron_fission_xs_offset"]
    size = nuclide["neutron_fission_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_fission_xs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_fission_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_elastic_scattering_reaction_IDs(index, nuclide, data, value):
    offset = nuclide["neutron_elastic_scattering_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def neutron_elastic_scattering_reaction_IDs_all(nuclide, data, value):
    start = nuclide["neutron_elastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_neutron_elastic_scattering_reaction"]
    end = start + size
    data[start:end] = value


@njit
def neutron_elastic_scattering_reaction_IDs_last(nuclide, data, value):
    start = nuclide["neutron_elastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_neutron_elastic_scattering_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_elastic_scattering_reaction_IDs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_elastic_scattering_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_capture_reaction_IDs(index, nuclide, data, value):
    offset = nuclide["neutron_capture_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def neutron_capture_reaction_IDs_all(nuclide, data, value):
    start = nuclide["neutron_capture_reaction_IDs_offset"]
    size = nuclide["N_neutron_capture_reaction"]
    end = start + size
    data[start:end] = value


@njit
def neutron_capture_reaction_IDs_last(nuclide, data, value):
    start = nuclide["neutron_capture_reaction_IDs_offset"]
    size = nuclide["N_neutron_capture_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_capture_reaction_IDs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_capture_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_inelastic_scattering_reaction_IDs(index, nuclide, data, value):
    offset = nuclide["neutron_inelastic_scattering_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def neutron_inelastic_scattering_reaction_IDs_all(nuclide, data, value):
    start = nuclide["neutron_inelastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_neutron_inelastic_scattering_reaction"]
    end = start + size
    data[start:end] = value


@njit
def neutron_inelastic_scattering_reaction_IDs_last(nuclide, data, value):
    start = nuclide["neutron_inelastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_neutron_inelastic_scattering_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_inelastic_scattering_reaction_IDs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_inelastic_scattering_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_fission_reaction_IDs(index, nuclide, data, value):
    offset = nuclide["neutron_fission_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def neutron_fission_reaction_IDs_all(nuclide, data, value):
    start = nuclide["neutron_fission_reaction_IDs_offset"]
    size = nuclide["N_neutron_fission_reaction"]
    end = start + size
    data[start:end] = value


@njit
def neutron_fission_reaction_IDs_last(nuclide, data, value):
    start = nuclide["neutron_fission_reaction_IDs_offset"]
    size = nuclide["N_neutron_fission_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_fission_reaction_IDs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_fission_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_fission_delayed_fractions(index, nuclide, data, value):
    offset = nuclide["neutron_fission_delayed_fractions_offset"]
    data[offset + index] = value


@njit
def neutron_fission_delayed_fractions_all(nuclide, data, value):
    start = nuclide["neutron_fission_delayed_fractions_offset"]
    size = nuclide["neutron_fission_delayed_fractions_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_fission_delayed_fractions_last(nuclide, data, value):
    start = nuclide["neutron_fission_delayed_fractions_offset"]
    size = nuclide["neutron_fission_delayed_fractions_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_fission_delayed_fractions_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_fission_delayed_fractions_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_fission_delayed_decay_rates(index, nuclide, data, value):
    offset = nuclide["neutron_fission_delayed_decay_rates_offset"]
    data[offset + index] = value


@njit
def neutron_fission_delayed_decay_rates_all(nuclide, data, value):
    start = nuclide["neutron_fission_delayed_decay_rates_offset"]
    size = nuclide["neutron_fission_delayed_decay_rates_length"]
    end = start + size
    data[start:end] = value


@njit
def neutron_fission_delayed_decay_rates_last(nuclide, data, value):
    start = nuclide["neutron_fission_delayed_decay_rates_offset"]
    size = nuclide["neutron_fission_delayed_decay_rates_length"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_fission_delayed_decay_rates_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_fission_delayed_decay_rates_offset"]
    end = start + length
    data[start:end] = value


@njit
def neutron_fission_delayed_spectrum_IDs(index, nuclide, data, value):
    offset = nuclide["neutron_fission_delayed_spectrum_IDs_offset"]
    data[offset + index] = value


@njit
def neutron_fission_delayed_spectrum_IDs_all(nuclide, data, value):
    start = nuclide["neutron_fission_delayed_spectrum_IDs_offset"]
    size = nuclide["N_neutron_fission_delayed_spectrum"]
    end = start + size
    data[start:end] = value


@njit
def neutron_fission_delayed_spectrum_IDs_last(nuclide, data, value):
    start = nuclide["neutron_fission_delayed_spectrum_IDs_offset"]
    size = nuclide["N_neutron_fission_delayed_spectrum"]
    end = start + size
    data[end - 1] = value


@njit
def neutron_fission_delayed_spectrum_IDs_chunk(start, length, nuclide, data, value):
    start += nuclide["neutron_fission_delayed_spectrum_IDs_offset"]
    end = start + length
    data[start:end] = value
